import { StyleThemeType } from './type/StyleThemeType';

export const lightTheme: StyleThemeType = {
  type: 'lightTheme',
  body: '#fff',
  headerBackground: '#fff',
  headerShadowColor: 'rgba(66,66,66,0.4)',
  menuText: '#000',
  menuActiveBackground: 'rgba(0,0,0,.05)',
  menuTextActive: '#000',
  text: '#363537',
  placeholderText: '#b1b0b1',
  containerBackground: '#F9F9F9',
  layerContainerBackground: '#D3D3D3',
  buttonPrimaryBackground: '#6979F8',
  buttonPrimaryBackgroundHover: '#4d53a7',
  buttonDangerBackground: '#FF647C',
  buttonSuccessBackground: '#00C48C',
  inputBackground: '#fff',
  buttonText: '#fff',
};

export const darkTheme: StyleThemeType = {
  type: 'darkTheme',
  body: '#363537',
  headerBackground: '#171618',
  headerShadowColor: 'rgba(250,250,250,0.2)',
  menuText: '#fff',
  menuActiveBackground: '#979294',
  menuTextActive: '#000',
  text: '#FAFAFA',
  placeholderText: '#5f5f5f',
  containerBackground: '#585858',
  layerContainerBackground: '#3f3d40',
  buttonPrimaryBackground: '#6979F8',
  buttonPrimaryBackgroundHover: '#4d53a7',
  buttonDangerBackground: '#FF647C',
  buttonSuccessBackground: '#00C48C',
  inputBackground: '#fff',
  buttonText: '#fff',
};
